[project]
name = "runner"
version = "0.1.2"
dependencies = [
	"autokitteh[all] ~= 0.4",
	"dill ~= 0.3",
	"grpcio ~= 1.68",
]

[project.optional-dependencies]
all = [
	# Development
	"ruff ~= 0.7",
	"pytest ~= 8.3",
]

[tool.setuptools.packages]
find = {}

[tool.pytest.ini_options]
addopts = """
	-v 
	--doctest-modules 
	--ignore tests/workflows
"""

[tool.ruff]
# Ignore protbuf generated files
extend-exclude = ["*.pyi", "*_pb2*.py"]

[tool.ruff.format]
quote-style = "double"
